package com.xworkz.collections.boot;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Iterator;

public class DamsRunner {

	public static void main(String[] args) {

		Collection<String> damsInKarnataka = new ArrayList<String>();

		damsInKarnataka.add("KRS");
		damsInKarnataka.add("bhadra dam");
		damsInKarnataka.add("tungabadra");
		damsInKarnataka.add("almatti");
		damsInKarnataka.add("basava sagara dam");
		damsInKarnataka.add("Raja Lakhamagouda dam");
		damsInKarnataka.add("Renuka Sagara");
		damsInKarnataka.add("Vani Vilasa Sagara");
		damsInKarnataka.add("Upper Tunga Dam");
		damsInKarnataka.add("Hemavathi Reservoir");
		damsInKarnataka.add("Kabini Reservoir");
		damsInKarnataka.add("Harangi Dam");
		damsInKarnataka.add("Linganamakki Dam[");
		damsInKarnataka.add("chakra dam");
		damsInKarnataka.add("Savehaklu");
		damsInKarnataka.add("mani");
		damsInKarnataka.add("supa");
		damsInKarnataka.add("kodasalli");
		damsInKarnataka.add("kadra");
		damsInKarnataka.add("shanti sagar");
		damsInKarnataka.add("karanji");

		Collection<String> damsInKerala = new ArrayList<String>();

		damsInKerala.add("Anathode Flanking");
		damsInKerala.add("anayirangal");
		damsInKerala.add("aruvikkare");
		damsInKerala.add("Azhutha Diversion Dam");
		damsInKerala.add("Cavaiar Dam");
		damsInKerala.add("Cheruthoni");
		damsInKerala.add("chimoni");
		damsInKerala.add("chulliar");
		damsInKerala.add("erattayar");
		damsInKerala.add("idamalayar");
		damsInKerala.add("idukki");
		damsInKerala.add("kakkayam");
		damsInKerala.add("kakki");
		damsInKerala.add("kallada");
		damsInKerala.add("kallar");
		damsInKerala.add("kallarkutty");
		damsInKerala.add("kanhiza puzha");
		damsInKerala.add("karapuzha");
		damsInKerala.add("kosani saddle");
		damsInKerala.add("kottagiri saddle");
		damsInKerala.add("kulamavu");
		damsInKerala.add("kullar");
		damsInKerala.add("kundala");
		damsInKerala.add("kuttiyar diversion");
		damsInKerala.add("kuttiyadi");
		damsInKerala.add("Kuttiyadi Aug. Saddle");
		damsInKerala.add("Kuttiyadi Spillway Dam");
		damsInKerala.add("lower periyal");
		damsInKerala.add("madupetty");
		damsInKerala.add("malampuza");
		damsInKerala.add("malankara");
		damsInKerala.add("mangalam");
		damsInKerala.add("meenar");
		damsInKerala.add("meenkara");
		damsInKerala.add("narakakanam diversion");
		damsInKerala.add("near kottagiri saddle");
		damsInKerala.add("neyyar");
		damsInKerala.add("pamba");
		damsInKerala.add("parambikulam");
		damsInKerala.add("peechi");
		damsInKerala.add("peppara");
		damsInKerala.add("periyar");
		damsInKerala.add("Peruvaripallam");
		damsInKerala.add("ponmudi");
		damsInKerala.add("poomala");
		damsInKerala.add("Poringalkuthu");
		damsInKerala.add("Pothundy");
		damsInKerala.add("Sengulam");
		damsInKerala.add("Sholayar");
		damsInKerala.add("Sholayar flanking");
		damsInKerala.add("Siruvani");
		damsInKerala.add("Tunacadavu");
		damsInKerala.add("Upper Moozhiyar");
		damsInKerala.add("Upper Moozhiyar Spillway");
		damsInKerala.add("Vazhany");
		damsInKerala.add("Vazhikkadavu");
		damsInKerala.add("Veluthoda Forebay");
		damsInKerala.add("Walayar");

		Collection<String> damsInAndraPradesh = new ArrayList<String>();

		damsInAndraPradesh.add("Ahoblam");
		damsInAndraPradesh.add("Akkapalem ");
		damsInAndraPradesh.add("alaganoor");
		damsInAndraPradesh.add("Ananthasagarm ");
		damsInAndraPradesh.add("Andra");
		damsInAndraPradesh.add("Arniar");
		damsInAndraPradesh.add("Bahuda");
		damsInAndraPradesh.add("Bhairavanithippa");
		damsInAndraPradesh.add("Bhupatipalem");
		damsInAndraPradesh.add("Buggavagu");
		damsInAndraPradesh.add("Bukkapatnam ");
		damsInAndraPradesh.add("Buggavanka");
		damsInAndraPradesh.add("Bukkapatnam");
		damsInAndraPradesh.add("chagallu barange");
		damsInAndraPradesh.add("annamayya");
		damsInAndraPradesh.add("Chennaraya");
		damsInAndraPradesh.add("Chintakuntavagu");
		damsInAndraPradesh.add("Chitravathi");
		damsInAndraPradesh.add("cumbum");
		damsInAndraPradesh.add("Dharmavaram");
		damsInAndraPradesh.add("Donkarai");
		damsInAndraPradesh.add("Eguva Thamballa Palli");
		damsInAndraPradesh.add("Forebay Lower Sileru");
		damsInAndraPradesh.add("Gajuladinne");
		damsInAndraPradesh.add("Gandicheruvu");
		damsInAndraPradesh.add("Gandipalem ");
		damsInAndraPradesh.add("Ghambiramgedda");
		damsInAndraPradesh.add("Guntawada Main Dam");
		damsInAndraPradesh.add("Haresamudram big");
		damsInAndraPradesh.add("Jajigedda");
		damsInAndraPradesh.add("Jalakanur");
		damsInAndraPradesh.add("Jalleru");
		damsInAndraPradesh.add("Jhanjhavathi");
		damsInAndraPradesh.add("Kalangi");
		damsInAndraPradesh.add("Kalyani");
		damsInAndraPradesh.add("Kampasamudram New");
		damsInAndraPradesh.add("Kandaleru");
		damsInAndraPradesh.add("Kanigiri");
		damsInAndraPradesh.add("Konam");
		damsInAndraPradesh.add("Kovvadakalva");
		damsInAndraPradesh.add("Krishnapuram");
		damsInAndraPradesh.add("Kumili");
		damsInAndraPradesh.add("Khushavati");
		damsInAndraPradesh.add("Lower Sagileru");
		damsInAndraPradesh.add("Madakasira");
		damsInAndraPradesh.add("Maddigedda");
		damsInAndraPradesh.add("Madduvalasa");
		damsInAndraPradesh.add("Mallimadugu");
		damsInAndraPradesh.add("Midpennar Stage-I/Mid-Pennar Dam");
		damsInAndraPradesh.add("Mopadu ");
		damsInAndraPradesh.add("Mararipalli");
		damsInAndraPradesh.add("Mylavaram");
		damsInAndraPradesh.add("Nagurur");
		damsInAndraPradesh.add("Nakkalagandi");
		damsInAndraPradesh.add("Narayanapuram");
		damsInAndraPradesh.add("Nellore");
		damsInAndraPradesh.add("P.T.Cheruvu");
		damsInAndraPradesh.add("Paleru ,Owk Dam");
		damsInAndraPradesh.add("Pampa");
		damsInAndraPradesh.add("Panthulu Cheruvu");
		damsInAndraPradesh.add("Paya Cheruvu");
		damsInAndraPradesh.add("Pedaballi Dam");
		damsInAndraPradesh.add("Pedda Cheruvu , Nagasamudram Dam");
		damsInAndraPradesh.add("Pedda Tippa Samudram Dam");
		damsInAndraPradesh.add("Tulasikrishan");
		damsInAndraPradesh.add("Peddagedda");
		damsInAndraPradesh.add("Peddayetivanka");
		damsInAndraPradesh.add("Pedderu");
		damsInAndraPradesh.add("Pendlur");
		damsInAndraPradesh.add("Perur Dam");
		damsInAndraPradesh.add("Pincha Dam");
		damsInAndraPradesh.add("Pittakayagulla");
		damsInAndraPradesh.add("Pulichintala");
		damsInAndraPradesh.add("Raiwada Dam");
		damsInAndraPradesh.add("Rallapadu Dam");
		damsInAndraPradesh.add("Rayalacheruvu Dam");
		damsInAndraPradesh.add("SPVBS");
		damsInAndraPradesh.add("Sadasivakona Dam");
		damsInAndraPradesh.add("Sancherla");
		damsInAndraPradesh.add("Sankarayelapeta Dam");
		damsInAndraPradesh.add("Seethaipally Dam");
		damsInAndraPradesh.add("Siddalagandi Dam");
		damsInAndraPradesh.add("Somasila Dam");
		damsInAndraPradesh.add("Sreerangarayani Cheruvu Dam");
		damsInAndraPradesh.add("Sri Tenneti Viswanatham Pedderu Dam");
		damsInAndraPradesh.add("Surampalem");
		damsInAndraPradesh.add("T.Sundupalli Dam");
		damsInAndraPradesh.add("Tajangi");
		damsInAndraPradesh.add("Thadukuvagu");
		damsInAndraPradesh.add("Thammileru");
		damsInAndraPradesh.add("Thandava");
		damsInAndraPradesh.add("Thandava");
		damsInAndraPradesh.add("Thatipudi");
		damsInAndraPradesh.add("Thippayapalem");
		damsInAndraPradesh.add("Upper Pennar");
		damsInAndraPradesh.add("Varadaraja Swamy Gudi");
		damsInAndraPradesh.add("Varaha");

		

		Collection<String> damsInGoa = new ArrayList<String>();

		damsInGoa.add("Anjunam Dam");
		damsInGoa.add("M.I. Dam");
		damsInGoa.add("Salaulim Dam");

		Collection<String> damsInArunachalPradesh = new ArrayList<String>();

		damsInAndraPradesh.add("Ranganadi");
		damsInAndraPradesh.add("Subansiri Lower HE");

		Collection<String> damsInAssam = new ArrayList<String>();

		damsInAssam.add("Karbi Langpi");
		damsInAssam.add("Umrong dam");

		Collection<String> damsInBihar = new ArrayList<String>();

		damsInBihar.add("amrity");
		damsInBihar.add("anjan");
		damsInBihar.add("badua");
		damsInBihar.add("Barnar");
		damsInBihar.add("baskund");
		damsInBihar.add("Belharna");
		damsInBihar.add("Bilasi");
		damsInBihar.add("Chandan");
		damsInBihar.add("Durgawati");
		damsInBihar.add("Gaighat");
		damsInBihar.add("Jalkund");
		damsInBihar.add("Job");
		damsInBihar.add("Kailash Ghati");
		damsInBihar.add("Khargpur Lake");
		damsInBihar.add("Kohira");
		damsInBihar.add("Kolmahadeo");
		damsInBihar.add("Morwy");
		damsInBihar.add("Nagi");
		damsInBihar.add("Nakti");
		damsInBihar.add("Orhni");
		damsInBihar.add("Phulwaria");
		damsInBihar.add("Sindhwarni");
		damsInBihar.add("Srikhandi");
		damsInBihar.add("Upper Kiul");

		Collection<String> damsInHaryana = new ArrayList<String>();

		damsInHaryana.add("kaushalya");

		Collection<String> damsInHimachalPradesh = new ArrayList<String>();

		damsInHimachalPradesh.add("Baira Siul");
		damsInHimachalPradesh.add("Bassi");
		damsInHimachalPradesh.add("Bhakra");
		damsInHimachalPradesh.add("Chamera I");
		damsInHimachalPradesh.add("Chamera II");
		damsInHimachalPradesh.add("Chamera III");
		damsInHimachalPradesh.add("Karchham-Wangtoo");
		damsInHimachalPradesh.add("kol");
		damsInHimachalPradesh.add("Largi");
		damsInHimachalPradesh.add("Malana I");
		damsInHimachalPradesh.add("Nathpa Jhakri");
		damsInHimachalPradesh.add("Pandoh");
		damsInHimachalPradesh.add("Parbati III");
		damsInHimachalPradesh.add("Parbati II");
		damsInHimachalPradesh.add("Sawra- Kuddu");
		damsInHimachalPradesh.add("Pong");

		Collection<String> damsInManipur = new ArrayList<String>();

		damsInManipur.add("Khoupum");
		damsInManipur.add("Khuja");
		damsInManipur.add("Singda");
		damsInManipur.add("thoubai");

		Collection<String> damsInMegalay = new ArrayList<String>();

		damsInMegalay.add("Khandong");
		damsInMegalay.add("Kyrdemkulai");
		damsInMegalay.add("Mawphlang");
		damsInMegalay.add("Myntdu-Leshka");
		damsInMegalay.add("Nongkhyllem");
		damsInMegalay.add("Nongkhyllem");

		Collection<String> damsInWestBengal = new ArrayList<String>();

		damsInWestBengal.add("Bakreshwar");
		damsInWestBengal.add("bandhu");
		damsInWestBengal.add("Bara mandir");
		damsInWestBengal.add("Barabhum");
		damsInWestBengal.add("beko");
		damsInWestBengal.add("Dangrajhore");
		damsInWestBengal.add("Dimu");
		damsInWestBengal.add("Futiary");
		damsInWestBengal.add("Golamarajore");
		damsInWestBengal.add("Hanumata");
		damsInWestBengal.add("Hinglow Irrigation Scheme Dam");
		damsInWestBengal.add("Kangsabati Kumari");
		damsInWestBengal.add("kanjan");
		damsInWestBengal.add("Karrior");
		damsInWestBengal.add("Khairabera ");
		damsInWestBengal.add("Kumari");
		damsInWestBengal.add("Lipania");
		damsInWestBengal.add("lower ppsp");
		damsInWestBengal.add("Moutorejore");
		damsInWestBengal.add("Muruguma");
		damsInWestBengal.add("Nachan Irri. Scheme");
		damsInWestBengal.add("Paraga Irri. Scheme");
		damsInWestBengal.add("patloi");
		damsInWestBengal.add("Ramchandrapur");
		damsInWestBengal.add("rupai");
		damsInWestBengal.add("Saharajore Irri. Scheme");
		damsInWestBengal.add("sali");
		damsInWestBengal.add("Taragonia Irri. Scheme");
		damsInWestBengal.add("tatko");
		damsInWestBengal.add("Teesta-III Lower");
		damsInWestBengal.add("Teesta-IV Lower");
		damsInWestBengal.add("Turga Irri. Scheme");
		damsInWestBengal.add("upper dam ppsp");

		Collection<String> damsInChattisgarh = new ArrayList<String>();
		
		damsInChattisgarh.add("Hasdeo Bango");
		damsInChattisgarh.add("Adpather Dam");
		damsInChattisgarh.add("Agarira");
		damsInChattisgarh.add("Ajabnagar");
		damsInChattisgarh.add("Amabeda");
		damsInChattisgarh.add("Amachuwa");
		damsInChattisgarh.add("Amakhokra");
		damsInChattisgarh.add("Amakoni");
		damsInChattisgarh.add("Amagon");
		damsInChattisgarh.add("Amakoni");
		damsInChattisgarh.add("Aondhi");
		damsInChattisgarh.add("Auramimunda");
		damsInChattisgarh.add("Ayabhandha");
		damsInChattisgarh.add("Badauli");
		damsInChattisgarh.add("Badesathi");
		damsInChattisgarh.add("Badra");
		damsInChattisgarh.add("Badrika Ashram");
		damsInChattisgarh.add("Ballar");
		damsInChattisgarh.add("Banjaridand");
		damsInChattisgarh.add("Banki");
		damsInChattisgarh.add("Bankipur");
		damsInChattisgarh.add("Barat Sagar");
		damsInChattisgarh.add("Bardar");
		damsInChattisgarh.add("Barkela");
		damsInChattisgarh.add("Barnai");
		damsInChattisgarh.add("Barota");
		damsInChattisgarh.add("Barpara");
		damsInChattisgarh.add("Batra");
		damsInChattisgarh.add("Beherakhar (Banjar )");
		damsInChattisgarh.add("Belbehra");
		damsInChattisgarh.add("Belhari");
		damsInChattisgarh.add("Bhagwantola");
		damsInChattisgarh.add("Bhopali");
		damsInChattisgarh.add("Bhoramdeo");
		damsInChattisgarh.add("Bhortola");
		damsInChattisgarh.add("Bhulsi");
		damsInChattisgarh.add("Bhursatoli");
		damsInChattisgarh.add("Binjali");
		damsInChattisgarh.add("Bisrampuri");
		damsInChattisgarh.add("Bordi");
		damsInChattisgarh.add("Chaker");
		damsInChattisgarh.add("Chamat");
		damsInChattisgarh.add("Champi");
		damsInChattisgarh.add("Chandra Nagar");
		damsInChattisgarh.add("Chanti");
		damsInChattisgarh.add("Charcha");
		damsInChattisgarh.add("Charpara");
		damsInChattisgarh.add("Chhirpani");
		damsInChattisgarh.add("Chhota Palgi");
		damsInChattisgarh.add("Chhuwari Pali");
		damsInChattisgarh.add("Chikhali");
		damsInChattisgarh.add("Chilputi");
		damsInChattisgarh.add("Chiniya");
		damsInChattisgarh.add("Chourasiya");
		damsInChattisgarh.add("Churiyapat");
		damsInChattisgarh.add("Dandgaon");
		damsInChattisgarh.add("Darki");
		damsInChattisgarh.add("Darritola");
		damsInChattisgarh.add("Deogaon");
		damsInChattisgarh.add("Deokatta");
		damsInChattisgarh.add("Deoripali");
		damsInChattisgarh.add("Dhab");
		damsInChattisgarh.add("Dhamni No. I");
		damsInChattisgarh.add("Dhanras");
		damsInChattisgarh.add("Dhara");
		damsInChattisgarh.add("Dhawanpur");
		damsInChattisgarh.add("Dhupkot");
		damsInChattisgarh.add("Diona");
		damsInChattisgarh.add("Doura");
		damsInChattisgarh.add("Dudhawa");
		damsInChattisgarh.add("Fatehpur");
		damsInChattisgarh.add("Fulwari");
		damsInChattisgarh.add("Gagnai");
		damsInChattisgarh.add("Ganeshpur");
		damsInChattisgarh.add("Gangpur");
		damsInChattisgarh.add("Ganiyari");
		damsInChattisgarh.add("Gatatola");
		damsInChattisgarh.add("Gej");
		damsInChattisgarh.add("Ghatoi");
		damsInChattisgarh.add("Ghoghra");
		damsInChattisgarh.add("Ghongha");
		damsInChattisgarh.add("Ghughwa");
		damsInChattisgarh.add("Ghumarapadar");
		damsInChattisgarh.add("Ghunghutta");
		damsInChattisgarh.add("Gobari");
		damsInChattisgarh.add("Gondli");
		damsInChattisgarh.add("Gouri");
		damsInChattisgarh.add("Gunderdehi");
		damsInChattisgarh.add("Gursia");
		damsInChattisgarh.add("Hathlewa");
		damsInChattisgarh.add("Jagannathpur");
		damsInChattisgarh.add("Jagatpur");
		damsInChattisgarh.add("Jamdih");
		damsInChattisgarh.add("Jhalpi");
		damsInChattisgarh.add("Jhingo");
		damsInChattisgarh.add("Jhumka");
		damsInChattisgarh.add("Junwani");
		damsInChattisgarh.add("Kachhod");
		damsInChattisgarh.add("Kadna");
		damsInChattisgarh.add("Kalidaraha");
		
		
		Collection<String> damsInGujarat = new ArrayList<String>();

		damsInGujarat.add("Aamli Chharchhoda");
		damsInGujarat.add("Abhalwad");
		damsInGujarat.add("Adhia");
		damsInGujarat.add("Adhochhani");
		damsInGujarat.add("Adhoi- I");
		damsInGujarat.add("Adpur");
		damsInGujarat.add("Advana");
		damsInGujarat.add("Aji I");
		damsInGujarat.add("Aji II");
		damsInGujarat.add("Aji III");
		damsInGujarat.add("Aji IV");
		damsInGujarat.add("Ajwa");
		damsInGujarat.add("Alan Sagar");
		damsInGujarat.add("Amalwant");
		damsInGujarat.add("Ambajal");
		damsInGujarat.add("Badi-Padva");
		damsInGujarat.add("Bagad");
		damsInGujarat.add("Baladhor");
		damsInGujarat.add("balamdi");
		damsInGujarat.add("Balapar Budadro");
		damsInGujarat.add("Baldeva");
		damsInGujarat.add("Baliyawad");
		damsInGujarat.add("Bamanbore");
		damsInGujarat.add("Bamathia- I");
		damsInGujarat.add("Bamathia- II");
		damsInGujarat.add("Bambhanka");
		damsInGujarat.add("Bandhara");
		damsInGujarat.add("Bandi");
		damsInGujarat.add("Bangawadi");
		damsInGujarat.add("Baranda");
		damsInGujarat.add("Baukha");
		damsInGujarat.add("Bedi");
		damsInGujarat.add("Bela");
		damsInGujarat.add("Berachiya");
		damsInGujarat.add("Bhadar II");
		damsInGujarat.add("Bhadar");
		damsInGujarat.add("Bhadreshwar");
		damsInGujarat.add("Bhaguda");
		damsInGujarat.add("Bhandaria");
		damsInGujarat.add("Bedi");
		damsInGujarat.add("Bhanmer");
		damsInGujarat.add("Bhanmer");
		damsInGujarat.add("Bharapar");
		damsInGujarat.add("Bharudia");
		damsInGujarat.add("Bhimdad");
		damsInGujarat.add("Bhogavo-II");
		damsInGujarat.add("Bhimdad");
		damsInGujarat.add("Chachka");
		damsInGujarat.add("Chandrabhaga");
		damsInGujarat.add("Chang");
		damsInGujarat.add("Chavadka");
		damsInGujarat.add("Chhaparvadi-II");
		damsInGujarat.add("Chhaparwadi-Lunivav");
		damsInGujarat.add("Chimnabai-Lake");
		damsInGujarat.add("Chonda");
		damsInGujarat.add("Chopadavav");
		damsInGujarat.add("Chorwadala");
		damsInGujarat.add("Dabahada");
		damsInGujarat.add("Dabasang");
		damsInGujarat.add("Dadar");
		damsInGujarat.add("Daiminisar");
		damsInGujarat.add("Dalvada");
		damsInGujarat.add("Dangra");
		damsInGujarat.add("Dantiwada");
		damsInGujarat.add("Daria");
		damsInGujarat.add("Dedarani");
		damsInGujarat.add("Dedhia");
		damsInGujarat.add("Demali");
		damsInGujarat.add("Edalwada");
		damsInGujarat.add("Ekalia");
		damsInGujarat.add("Facharia");
		damsInGujarat.add("Faddanbeti");
		damsInGujarat.add("Fakirwadi");
		damsInGujarat.add("Falku");
		damsInGujarat.add("Faradi");
		damsInGujarat.add("Farera");
		damsInGujarat.add("Fatehgadh");
		damsInGujarat.add("Fodaraness");
		damsInGujarat.add("Fulra");
		damsInGujarat.add("Fulzar I");
		damsInGujarat.add("Gajansagar");
		damsInGujarat.add("Demali");
		damsInGujarat.add("Gajod");
		damsInGujarat.add("Galath");
		damsInGujarat.add("Gaurishankar Lake");
		damsInGujarat.add("Gautameshwar Lake");
		damsInGujarat.add("Gebanshapir");
		damsInGujarat.add("Ghee");
		damsInGujarat.add("Ghodadharoi");
		damsInGujarat.add("Godechi");
		damsInGujarat.add("Godhatad");
		damsInGujarat.add("Gokhalana");
		damsInGujarat.add("Gondali");
		damsInGujarat.add("Goma");
		damsInGujarat.add("Goyala");
		damsInGujarat.add("Goyasundal");
		damsInGujarat.add("Gugariyana");
		damsInGujarat.add("Guhai");
		damsInGujarat.add("Guneli");
		damsInGujarat.add("Hadaf");
		damsInGujarat.add("Halara");
		damsInGujarat.add("Hamapur");
		damsInGujarat.add("Hamipara");
		
		
		Collection<String> damsInJharkhand = new ArrayList<String>();
		
		damsInJharkhand.add("Amanat");
		damsInJharkhand.add("Anjanwa");
		damsInJharkhand.add("Anraj");
		damsInJharkhand.add("Baksa");
		damsInJharkhand.add("Bandha");
		damsInJharkhand.add("Baranadi");
		damsInJharkhand.add("Barhi");
		damsInJharkhand.add("Basuki");
		damsInJharkhand.add("Batane");
		damsInJharkhand.add("Batre");
		damsInJharkhand.add("Bhairwa");
		damsInJharkhand.add("Bhavnikhand");
		damsInJharkhand.add("Bhutanduba");
		damsInJharkhand.add("Bucha Opa");
		damsInJharkhand.add("Burhai");
		damsInJharkhand.add("Chandil");
		damsInJharkhand.add("Chatania Ghat");
		damsInJharkhand.add("Chinda");
		damsInJharkhand.add("Chirka");
		damsInJharkhand.add("Danro");
		damsInJharkhand.add("Dhankai");
		damsInJharkhand.add("Dhansingtoli");
		damsInJharkhand.add("Dhulki");
		damsInJharkhand.add("Diggalpahari");
		damsInJharkhand.add("Garhi");
		damsInJharkhand.add("Getalsud");
		damsInJharkhand.add("Ghagra");
		damsInJharkhand.add("Gonda");
		damsInJharkhand.add("Hatia");
		damsInJharkhand.add("Hiru");
		damsInJharkhand.add("Icha");
		damsInJharkhand.add("Jaipur");
		damsInJharkhand.add("Jamunia");
		damsInJharkhand.add("Jenasai");
		damsInJharkhand.add("JJharjhara");
		damsInJharkhand.add("Kanhar");
		damsInJharkhand.add("Kans");
		damsInJharkhand.add("Kansjore");
		damsInJharkhand.add("Katri");
		damsInJharkhand.add("Kesho");
		damsInJharkhand.add("Khudia");
		damsInJharkhand.add("Konar");
		damsInJharkhand.add("Larwa");
		damsInJharkhand.add("Latratu");
		damsInJharkhand.add("Left banki");
		damsInJharkhand.add("Lorgara");
		damsInJharkhand.add("Lotia");
		damsInJharkhand.add("Maithon");
		damsInJharkhand.add("Malay");
		damsInJharkhand.add("Masonjor JH");
		damsInJharkhand.add("Masaria");
		damsInJharkhand.add("Murahir");
		damsInJharkhand.add("Nakti");
		damsInJharkhand.add("Nalkari");
		damsInJharkhand.add("Nandini");
		damsInJharkhand.add("North koel");
		damsInJharkhand.add("Palna");
		damsInJharkhand.add("Panchat Hill");
		damsInJharkhand.add("Panchkhero");
		damsInJharkhand.add("Pandarwa");
		damsInJharkhand.add("Paras");
		damsInJharkhand.add("Punasi");
		damsInJharkhand.add("Raisa");
		damsInJharkhand.add("Ramrekha");
		damsInJharkhand.add("Salaiya");
		damsInJharkhand.add("Satpotka");
		damsInJharkhand.add("Sitaram pur");
		damsInJharkhand.add("Sonua");
		damsInJharkhand.add("Sudhari Nala");
		damsInJharkhand.add("Sugathan");
		damsInJharkhand.add("Sukri");
		damsInJharkhand.add("Sunder");
		damsInJharkhand.add("Sunder");
		damsInJharkhand.add("Surang");
		damsInJharkhand.add("Suryodi");
		damsInJharkhand.add("Tahlay");
		damsInJharkhand.add("Tajna");
		damsInJharkhand.add("Tapkara");
		damsInJharkhand.add("Temrain");
		damsInJharkhand.add("Tenughat");
		damsInJharkhand.add("Tilaiya");
		damsInJharkhand.add("Torai");
		damsInJharkhand.add("Torlow");
		damsInJharkhand.add("Upper Shankh");		
		
		Collection<String> damsInMadhyaPradesh = new ArrayList<String>();
		
		damsInMadhyaPradesh.add("Adampura");
		damsInMadhyaPradesh.add("Adner");
		damsInMadhyaPradesh.add("Agar agari");
		damsInMadhyaPradesh.add("Agar");
		damsInMadhyaPradesh.add("Ahirkheda");
		damsInMadhyaPradesh.add("Ahmadpur");
		damsInMadhyaPradesh.add("Akhajhiri");		
		damsInMadhyaPradesh.add("Akhetpur");
		damsInMadhyaPradesh.add("Ama (Old)");
		damsInMadhyaPradesh.add("Amadehi");
		damsInMadhyaPradesh.add("Amadi");
		damsInMadhyaPradesh.add("Amahi");
		damsInMadhyaPradesh.add("Amarpur");
		damsInMadhyaPradesh.add("Amba");
		damsInMadhyaPradesh.add("Ambabarod");
		damsInMadhyaPradesh.add("Ambak");
		damsInMadhyaPradesh.add("Ambakhal");
		damsInMadhyaPradesh.add("Ambari");
		damsInMadhyaPradesh.add("Amjhar");
		damsInMadhyaPradesh.add("Amkoi");
		damsInMadhyaPradesh.add("Amlabardia");
		damsInMadhyaPradesh.add("Amlipada- I");
		damsInMadhyaPradesh.add("Amlipada- II");
		damsInMadhyaPradesh.add("Amrabad");
		damsInMadhyaPradesh.add("Amua");
		damsInMadhyaPradesh.add("Amwar Saddle");
		damsInMadhyaPradesh.add("Anandikhedi");
		damsInMadhyaPradesh.add("Anjarda No. I");
		
		damsInMadhyaPradesh.add("Anoo");
		damsInMadhyaPradesh.add("Antalwasa");
		damsInMadhyaPradesh.add("Aoda");
		damsInMadhyaPradesh.add("Ari");
		damsInMadhyaPradesh.add("Arnia Bahadarpur");
		damsInMadhyaPradesh.add("Asawati");
		damsInMadhyaPradesh.add("Ashok Nagar");
		damsInMadhyaPradesh.add("Atari");
		damsInMadhyaPradesh.add("Athawa");
		damsInMadhyaPradesh.add("Auria");
		damsInMadhyaPradesh.add("Awalia");
		damsInMadhyaPradesh.add("Badalpur");
		damsInMadhyaPradesh.add("Badera");
		damsInMadhyaPradesh.add("Badi Baodi");
		damsInMadhyaPradesh.add("Bagadih");
		damsInMadhyaPradesh.add("Bagan");
		damsInMadhyaPradesh.add("Bagdia No. II");
		damsInMadhyaPradesh.add("Bagharru");
		damsInMadhyaPradesh.add("Bagla");
		damsInMadhyaPradesh.add("Bah");
		damsInMadhyaPradesh.add("Bahniakhedi");
		damsInMadhyaPradesh.add("Bairar");
		damsInMadhyaPradesh.add("Baisly");
		damsInMadhyaPradesh.add("Bakeli");
		damsInMadhyaPradesh.add("Balasamund");
		damsInMadhyaPradesh.add("Bahniakhedi");
		damsInMadhyaPradesh.add("Balia");
		damsInMadhyaPradesh.add("Baliya");
		damsInMadhyaPradesh.add("Balwantpura");
		damsInMadhyaPradesh.add("Bamera");
		damsInMadhyaPradesh.add("Bamhodi");
		damsInMadhyaPradesh.add("Banchor");
		damsInMadhyaPradesh.add("Bandha");
		damsInMadhyaPradesh.add("Bandia");
		damsInMadhyaPradesh.add("Bangai");
		damsInMadhyaPradesh.add("Banganga");
		damsInMadhyaPradesh.add("Bankuiya");
		damsInMadhyaPradesh.add("Banna");
		damsInMadhyaPradesh.add("Bansagar");
		damsInMadhyaPradesh.add("Bansichikhli");
		damsInMadhyaPradesh.add("Banskheda");
		damsInMadhyaPradesh.add("Baramandal");
		damsInMadhyaPradesh.add("Barana Bamori");
		damsInMadhyaPradesh.add("Barbaspur");
		damsInMadhyaPradesh.add("Barana Bamori");
		damsInMadhyaPradesh.add("Barbet I");
		damsInMadhyaPradesh.add("Barbet II");
		damsInMadhyaPradesh.add("Barbuspur");
		damsInMadhyaPradesh.add("Bardevla");
		damsInMadhyaPradesh.add("Baretha");
		damsInMadhyaPradesh.add("Bargona");
		damsInMadhyaPradesh.add("Chanderi");
		damsInMadhyaPradesh.add("Chandgarh");
		damsInMadhyaPradesh.add("Chandoor");
		damsInMadhyaPradesh.add("Chandrakeshar");
		damsInMadhyaPradesh.add("Changoba");
		damsInMadhyaPradesh.add("Chapper");
		damsInMadhyaPradesh.add("Chargaon");
		damsInMadhyaPradesh.add("Charkhari");
		damsInMadhyaPradesh.add("Chawarpani");
		damsInMadhyaPradesh.add("Chhapani");
		damsInMadhyaPradesh.add("Chhapari");
		damsInMadhyaPradesh.add("Chhapi");
		damsInMadhyaPradesh.add("Chhewla");
		damsInMadhyaPradesh.add("Chhotakidhar");
		damsInMadhyaPradesh.add("Chhoti Deori");
		damsInMadhyaPradesh.add("Dabri");
		damsInMadhyaPradesh.add("Dadla");
		damsInMadhyaPradesh.add("Dagarkot");
		damsInMadhyaPradesh.add("Dahod");
		damsInMadhyaPradesh.add("Dalka Banda");
		damsInMadhyaPradesh.add("Daroli");
		damsInMadhyaPradesh.add("Data Dogari");
		damsInMadhyaPradesh.add("Datia");
		damsInMadhyaPradesh.add("Datoda");
		damsInMadhyaPradesh.add("Dedla");
		damsInMadhyaPradesh.add("Deep sagar");
	
	
		Collection<String> damsInMaharastra = new ArrayList<String>();
	
		damsInMaharastra.add("Dhamapur");
		damsInMaharastra.add("Vihar");
		damsInMaharastra.add("Ekrukh");
		damsInMaharastra.add("Shirsufal");
		damsInMaharastra.add("Tulshi");
		damsInMaharastra.add("Khadakwasla");
		damsInMaharastra.add("Ashti");
		damsInMaharastra.add("Mhaswad");
		damsInMaharastra.add("Tensa");
		damsInMaharastra.add("Shetfal");
		damsInMaharastra.add("Khairbandha");
		damsInMaharastra.add("Pathari");
		damsInMaharastra.add("Chankapur");
		damsInMaharastra.add("Ramtek");
		damsInMaharastra.add("Chandpur");
		damsInMaharastra.add("Walwan");
		damsInMaharastra.add("Dama");
		damsInMaharastra.add("Bodalkasa");
		damsInMaharastra.add("Shirvata");
		damsInMaharastra.add("Asolamendha");
		damsInMaharastra.add("Thokarwadi");
		damsInMaharastra.add("Chorkhamara");
		damsInMaharastra.add("Ghorazari");
		damsInMaharastra.add("Bhandardara");
		damsInMaharastra.add("Mulshi");
		damsInMaharastra.add("Mas");
		damsInMaharastra.add("Ghanewadi");
		damsInMaharastra.add("Visapur");
		damsInMaharastra.add("Radhanagari");
		damsInMaharastra.add("Vaitarna");
		damsInMaharastra.add("Purmepeda");
		damsInMaharastra.add("Khasapur");
		damsInMaharastra.add("Dheku");
		damsInMaharastra.add("Sindphana");
		damsInMaharastra.add("Ekburji");
		damsInMaharastra.add("Khelocala");
		damsInMaharastra.add("Upper Dudhana");
		damsInMaharastra.add("Koyna");
		damsInMaharastra.add("Gangapur");
		damsInMaharastra.add("Bor");
		damsInMaharastra.add("Ghod");
		damsInMaharastra.add("Tisangi");
		damsInMaharastra.add("Wunna");
		damsInMaharastra.add("Galhati");
		damsInMaharastra.add("Mangi");
		damsInMaharastra.add("Mehakari");
		damsInMaharastra.add("Bhudihal");
		damsInMaharastra.add("Wan");
		damsInMaharastra.add("Nawegaonbandh");
		damsInMaharastra.add("Pandherbodi");
		damsInMaharastra.add("Kurje");
		damsInMaharastra.add("Nalganga");
		damsInMaharastra.add("Sukhana");
		damsInMaharastra.add("Kumur");
		damsInMaharastra.add("Manur");
		damsInMaharastra.add("Yeldari");
		damsInMaharastra.add("Anjani");
		damsInMaharastra.add("Siddheshwar");
		damsInMaharastra.add("Kundrala");
		damsInMaharastra.add("Gharni");
		damsInMaharastra.add("Dolwahal");
		damsInMaharastra.add("Girna");
		damsInMaharastra.add("Malangaon");
		damsInMaharastra.add("Karwand");
		damsInMaharastra.add("Itiadoh");
		damsInMaharastra.add("Sirpur");
		damsInMaharastra.add("Pujaritola");
		damsInMaharastra.add("Terna");
		damsInMaharastra.add("Morna");
		damsInMaharastra.add("Gyanganga");
		damsInMaharastra.add("Upper Pus");
		damsInMaharastra.add("Malkhed");
		damsInMaharastra.add("Tanajisagar");
		damsInMaharastra.add("Pawana");
		damsInMaharastra.add("Kalyangirija");
		damsInMaharastra.add("Bhojapur");
		damsInMaharastra.add("Saikheda");
		damsInMaharastra.add("Mula");
		damsInMaharastra.add("Upper Vaitarana");
		damsInMaharastra.add("Panzara");
		damsInMaharastra.add("Yeralwadi");
		damsInMaharastra.add("Manyad");
		damsInMaharastra.add("Chulbandh");
		damsInMaharastra.add("Dhamna");
		damsInMaharastra.add("Dino");
		damsInMaharastra.add("Kanoli");
		damsInMaharastra.add("Nazare");
		damsInMaharastra.add("Karanjwan");
		damsInMaharastra.add("Katepurna");
		damsInMaharastra.add("Nirguna");
		damsInMaharastra.add("Karpera");
		damsInMaharastra.add("Palkhed");
		damsInMaharastra.add("Kanholibara");
		damsInMaharastra.add("Vir Baji Pasalkar");
		damsInMaharastra.add("Alwandi");
		damsInMaharastra.add("Adhala");
		damsInMaharastra.add("Tiru");
		damsInMaharastra.add("Kamthikhairy");
		damsInMaharastra.add("Jayakwadi");
		damsInMaharastra.add("Jakapur");
		damsInMaharastra.add("Pargaon Ghatshil");
		
		Collection<String> damsInMizoram = new ArrayList<String>();
	
		damsInMizoram.add("Serlui B Dam");
		damsInMizoram.add("Tuirial Dam");

		Collection<String> damsInNagaland = new ArrayList<String>();
	
		damsInNagaland.add("Doyang Hep");
	
		Collection<String> damsInOdisha = new ArrayList<String>();
	
		damsInOdisha.add("Alubani");
		damsInOdisha.add("Aradei");
		damsInOdisha.add("Arikul");
		damsInOdisha.add("Badabandha");
		damsInOdisha.add("Badanalla");
		damsInOdisha.add("Badjore");
		damsInOdisha.add("Baghalati");
		damsInOdisha.add("Baghjharan");
		damsInOdisha.add("Baghua");
		damsInOdisha.add("Balaskumpa");
		damsInOdisha.add("Balimela");
		damsInOdisha.add("Bankabal");
		damsInOdisha.add("Banksal");
		damsInOdisha.add("Baura");
		damsInOdisha.add("Bautia");
		damsInOdisha.add("Bedapada");
		damsInOdisha.add("Behera");
		damsInOdisha.add("Bhagirijhala");
		damsInOdisha.add("Bhallugahi");
		damsInOdisha.add("Bhaluguda");
		damsInOdisha.add("Bhanjanagar");
		damsInOdisha.add("Bhaskel");
		damsInOdisha.add("Bhatrajore");
		damsInOdisha.add("Chhamundia");
		damsInOdisha.add("Chhatenjore");
		damsInOdisha.add("Chheligada");
		damsInOdisha.add("Dadara Ghati");
		damsInOdisha.add("Daha");
		damsInOdisha.add("Dasamanthapur");
		damsInOdisha.add("Damsal");
		damsInOdisha.add("Debijharan");
		damsInOdisha.add("Deo");
		damsInOdisha.add("Deojharan");
		damsInOdisha.add("Derjang");
		damsInOdisha.add("Dhanei");
		damsInOdisha.add("Dhulipaunsia");
		damsInOdisha.add("Domkutch");
		damsInOdisha.add("Dumerbahal");
		damsInOdisha.add("Gaikhai");
		damsInOdisha.add("Ganianalla");
		damsInOdisha.add("Garh");
		damsInOdisha.add("Gayapatha");
		damsInOdisha.add("Ghagara");
		damsInOdisha.add("Ghatakeswar");
		damsInOdisha.add("Ghodahada");
		damsInOdisha.add("Gohira");
		damsInOdisha.add("Goibali");
		damsInOdisha.add("Gundurapasi");
		damsInOdisha.add("Gurlijore");
		damsInOdisha.add("HATIANALLA M.I.P");
		damsInOdisha.add("Hadua");
		damsInOdisha.add("Haguri");
		damsInOdisha.add("Haladia");
		damsInOdisha.add("Harabhangi");
		damsInOdisha.add("Hariharjore");
		damsInOdisha.add("Haripur");
		damsInOdisha.add("Hirakud");
		damsInOdisha.add("Indrawati");
		damsInOdisha.add("Jagadala");
		damsInOdisha.add("Jaigarh");
		damsInOdisha.add("Jalaput");
		damsInOdisha.add("Jambhira");
		damsInOdisha.add("Jamboonala");
		damsInOdisha.add("Jamuna Bundha");
		damsInOdisha.add("Jaunria");
		damsInOdisha.add("Jharanai");
		damsInOdisha.add("Jharbandha");
		damsInOdisha.add("Jhumuka");
		damsInOdisha.add("Jodabadia");
		damsInOdisha.add("Kakudajodi");
		damsInOdisha.add("Kalakala");
		damsInOdisha.add("Kalijodi");
		damsInOdisha.add("Kolo");
		damsInOdisha.add("Kangani");
		damsInOdisha.add("Kanheinalla");
		damsInOdisha.add("Kanjhari");
		damsInOdisha.add("Kansabansa");
		damsInOdisha.add("Kansbahal");
		damsInOdisha.add("Kanteijhara");
		damsInOdisha.add("Kantesir");
		damsInOdisha.add("Kanupur");
		damsInOdisha.add("Kapur");
		damsInOdisha.add("Karada");
		damsInOdisha.add("Karanjkote");
		damsInOdisha.add("Khadakhai");
		damsInOdisha.add("Khajuria");
		damsInOdisha.add("Khandijharan");
		damsInOdisha.add("Lower Indra");
		damsInOdisha.add("Liar");
		damsInOdisha.add("Mahisanalla");
		damsInOdisha.add("Malakangiri");
		damsInOdisha.add("Manjhor");
		damsInOdisha.add("Mandira");
		damsInOdisha.add("Marudi");
		damsInOdisha.add("Masina");
		damsInOdisha.add("Mathan Pal");
		damsInOdisha.add("Mathili");
		damsInOdisha.add("Pansapal");
		damsInOdisha.add("Parhal");
		damsInOdisha.add("Pilasalki");
		
		Collection<String> damsInPunjab = new ArrayList<String>();
		
		damsInPunjab.add("Chohal");
		damsInPunjab.add("Damsal");
		damsInPunjab.add("Dholbaha");
		damsInPunjab.add("Jainti");
		damsInPunjab.add("Janauri");
		damsInPunjab.add("Maili");
		damsInPunjab.add("Mirzapur");
		damsInPunjab.add("Patiari");
		damsInPunjab.add("Perch");
		damsInPunjab.add("Ranjit Sagar");
		damsInPunjab.add("Saleran");
		damsInPunjab.add("Shahpur Kandi");
		damsInPunjab.add("Siswan");
		damsInPunjab.add("Thana");
		
		Collection<String> damsInRajasthan = new ArrayList<String>();
		
		damsInRajasthan.add("Abhaypura");
		damsInRajasthan.add("Alnia");
		damsInRajasthan.add("Amli Kheda");
		damsInRajasthan.add("Angore");
		damsInRajasthan.add("Anwasa");
		damsInRajasthan.add("Arwar");
		damsInRajasthan.add("Atawara");
		damsInRajasthan.add("Babara");
		damsInRajasthan.add("Badgaon");
		damsInRajasthan.add("Bagolia");
		damsInRajasthan.add("Bajrang Garh");
		damsInRajasthan.add("Bandi Sandhara");
		damsInRajasthan.add("Banakiya");
		damsInRajasthan.add("Bankali");
		damsInRajasthan.add("Baradapura");
		damsInRajasthan.add("Bari Mansarowar");
		damsInRajasthan.add("Barkheri");
		damsInRajasthan.add("Bassi");
		damsInRajasthan.add("Basundni");
		damsInRajasthan.add("Bhagora");
		damsInRajasthan.add("Bhagwatgardh");
		damsInRajasthan.add("Bhamri Tandi");
		damsInRajasthan.add("Bhagora");
		damsInRajasthan.add("Bhanwar Semla");
		damsInRajasthan.add("Bhimlat");
		damsInRajasthan.add("Bhimsagar");
		damsInRajasthan.add("Bhopal Sagar");
		damsInRajasthan.add("Bilas");
		damsInRajasthan.add("Bhula");
		damsInRajasthan.add("Bisalpur");
		damsInRajasthan.add("Bithan");
		damsInRajasthan.add("Biya pada");
		damsInRajasthan.add("Bithan");
		damsInRajasthan.add("Borda");
		damsInRajasthan.add("Boria");
		damsInRajasthan.add("Buchara");
		damsInRajasthan.add("Bundika Gothra");
		damsInRajasthan.add("Burdha");
		damsInRajasthan.add("Butri");
		damsInRajasthan.add("Chacha Kheri");
		damsInRajasthan.add("Chandelao");
		damsInRajasthan.add("Chandrabhaga");
		damsInRajasthan.add("Chandrana");
		damsInRajasthan.add("Chandsen Bheru");
		damsInRajasthan.add("Chaparwara");
		damsInRajasthan.add("Chatra Kunty");
		damsInRajasthan.add("Chatra Sagar");
		damsInRajasthan.add("Chauli");
		damsInRajasthan.add("Chhapi");
		damsInRajasthan.add("Chikalwar");
		damsInRajasthan.add("Chittoli");
		damsInRajasthan.add("Choti-Tandi");
		damsInRajasthan.add("Deopura");
		damsInRajasthan.add("Daya");
		damsInRajasthan.add("Deoriya");
		damsInRajasthan.add("Dhanta");
		damsInRajasthan.add("Domti Kokra");
		damsInRajasthan.add("Dheel");
		damsInRajasthan.add("Dunglawani");
		damsInRajasthan.add("Dugari");
		damsInRajasthan.add("Dudka II");
		damsInRajasthan.add("Dorai");
		damsInRajasthan.add("Fateh Sagar");
		damsInRajasthan.add("Gadola");
		damsInRajasthan.add("Galai Sagar");
		damsInRajasthan.add("Gagrin");
		damsInRajasthan.add("Galwa");
		damsInRajasthan.add("Galwania");
		damsInRajasthan.add("Gambhiri");
		damsInRajasthan.add("Gararda");
		damsInRajasthan.add("Girinanda");
		damsInRajasthan.add("Giroliya");
		damsInRajasthan.add("Godana");
		damsInRajasthan.add("Gopalpura");
		damsInRajasthan.add("Gosunda");
		damsInRajasthan.add("Govta");
		damsInRajasthan.add("Gosunda");
		damsInRajasthan.add("Gudha");
		damsInRajasthan.add("Gulandi");
		damsInRajasthan.add("Hamja Kheri");
		damsInRajasthan.add("Harish Chandra sagar");
		damsInRajasthan.add("Hemavas Saddle");
		damsInRajasthan.add("Hemawas");
		damsInRajasthan.add("Himmatgarhi");
		damsInRajasthan.add("Hindlot");
		damsInRajasthan.add("Hingonia");
		damsInRajasthan.add("Jagpura");
		damsInRajasthan.add("Jai Samand");
		damsInRajasthan.add("Jaisamand");
		damsInRajasthan.add("Jakham Main");
		damsInRajasthan.add("Jaswant Sagar");
		damsInRajasthan.add("Jawahar Sagar");
		damsInRajasthan.add("Jeerawal");
		damsInRajasthan.add("Jetpura");
		damsInRajasthan.add("Jhadol");
		damsInRajasthan.add("Juna Malari");
		damsInRajasthan.add("Juggar");
		damsInRajasthan.add("Kadambri");
		damsInRajasthan.add("Kala Bhata");
		damsInRajasthan.add("Kaladeh");
		
		Collection<String> damsInSikkim = new ArrayList<String>();
		
		damsInSikkim.add("Rangit III");
		damsInSikkim.add("Rangpo");
		damsInSikkim.add("Rongli");
		damsInSikkim.add("Teesta -V (NHPC)");
		damsInSikkim.add("Teesta-III");
		damsInSikkim.add("Teesta-IV");
		
		Collection<String> damsInTamilNadu = new ArrayList<String>();
		
		damsInTamilNadu.add("Aanaimaduvu");
		damsInTamilNadu.add("Adavinainarkovil");
		damsInTamilNadu.add("Amaravathi");
		damsInTamilNadu.add("Aliyar");
		damsInTamilNadu.add("Anaikuttam");
		damsInTamilNadu.add("Andiappanur Odai");
		damsInTamilNadu.add("Avalanche");
		damsInTamilNadu.add("Berijam");
		damsInTamilNadu.add("Barur");
		damsInTamilNadu.add("Bungihalla");
		damsInTamilNadu.add("Chembarambakkam");
		damsInTamilNadu.add("Chittar I");
		damsInTamilNadu.add("Chinnar");
		damsInTamilNadu.add("Chittar II");
		damsInTamilNadu.add("East Varahapallam");
		damsInTamilNadu.add("Emerald");
		damsInTamilNadu.add("Eravangalar");
		damsInTamilNadu.add("Gatana");
		damsInTamilNadu.add("Glenmorgan");
		damsInTamilNadu.add("Glenmorgan Forbay");
		damsInTamilNadu.add("Golwarpatti");
		damsInTamilNadu.add("Gomukhinadi");
		damsInTamilNadu.add("Gunderipallam");
		damsInTamilNadu.add("Gundar");
		damsInTamilNadu.add("Highwavys");
		damsInTamilNadu.add("Irukkangudi");
		damsInTamilNadu.add("Kadamparai");
		damsInTamilNadu.add("Kamraju Sagar");
		damsInTamilNadu.add("Kariakoil");
		damsInTamilNadu.add("Kesarigulihalla");
		damsInTamilNadu.add("Kuppanatham");
		damsInTamilNadu.add("Mambazhathuraiyar");
		damsInTamilNadu.add("Kuppanatham");
		damsInTamilNadu.add("Manalar");
		damsInTamilNadu.add("Manimukthanadhi");
		damsInTamilNadu.add("Manimuthar");
		damsInTamilNadu.add("Maravakandi Forbay");
		damsInTamilNadu.add("Marudhanadi");
		damsInTamilNadu.add("Mirugandanadhi");
		damsInTamilNadu.add("Mordhana");
		damsInTamilNadu.add("Moyar Forebay");
		damsInTamilNadu.add("Nagavathi");
		damsInTamilNadu.add("Nambiar");
		damsInTamilNadu.add("Nanganjiyar");
		damsInTamilNadu.add("Nilayur Bed");
		damsInTamilNadu.add("Noyyal Athupalayam");
		damsInTamilNadu.add("Noyyal Orathupalayam");
		damsInTamilNadu.add("Papanasam");
		damsInTamilNadu.add("Pambar");
		damsInTamilNadu.add("Parappalar ");
		damsInTamilNadu.add("Pechiparai");
		damsInTamilNadu.add("Pegumbahallah Forebay");
		damsInTamilNadu.add("Periyar Forebay");
		damsInTamilNadu.add("Perumpallam");
		damsInTamilNadu.add("Perunchani");
		damsInTamilNadu.add("Pilavukkal Kovilar");
		damsInTamilNadu.add("Pilavukkal Periyar");
		damsInTamilNadu.add("Pillur");
		damsInTamilNadu.add("Poigaiyar");
		damsInTamilNadu.add("Ponnaniar");
		damsInTamilNadu.add("Poondi");
		damsInTamilNadu.add("Porthimund");
		damsInTamilNadu.add("Puthen");
		damsInTamilNadu.add("Pykara");
		damsInTamilNadu.add("Rajathope Kanar");
		damsInTamilNadu.add("Ramanadhi");
		damsInTamilNadu.add("Sathanur");
		damsInTamilNadu.add("Sathiyar");
		damsInTamilNadu.add("Servalar");
		damsInTamilNadu.add("Shanmuganadhi");
		damsInTamilNadu.add("Shenbagathope");
		damsInTamilNadu.add("Sholayar");
		damsInTamilNadu.add("Shoolagiri Chinnar");
		damsInTamilNadu.add("Siddhamalli");
		damsInTamilNadu.add("Sothupparai");
		damsInTamilNadu.add("Thirumurthi");
		damsInTamilNadu.add("Thoppaiyar");
		damsInTamilNadu.add("Thumblahalli");
		damsInTamilNadu.add("Uppar(Erode)");
		damsInTamilNadu.add("Upper Aliyar");
		damsInTamilNadu.add("Upper Bhavani");
		damsInTamilNadu.add("Upper Kodayar");
		damsInTamilNadu.add("Upper Kodayar Diversion");
		damsInTamilNadu.add("Thumblahalli");
		damsInTamilNadu.add("Vadakku Paichaiyar");
		damsInTamilNadu.add("Vaigai");
		damsInTamilNadu.add("Vaniar");
		damsInTamilNadu.add("Varadhamanadhi");
		damsInTamilNadu.add("Varattar");
		damsInTamilNadu.add("Varattupallam");
		damsInTamilNadu.add("Vattamalaikarai Odai");
		damsInTamilNadu.add("Vembakottai");
		damsInTamilNadu.add("Vennir-Ar");
		damsInTamilNadu.add("Vidur");
		damsInTamilNadu.add("West Varahapallam Weir");
		damsInTamilNadu.add("Western Catchment No. I");
		damsInTamilNadu.add("Western Catchment No. II");
		damsInTamilNadu.add("Western Catchment No. III");
		damsInTamilNadu.add("Willington");
		
		Collection<String> damsInTelangana = new ArrayList<String>();
		
		damsInTelangana.add("Ada Village - Peddavagu");
		damsInTelangana.add("Akkampalli");
		damsInTelangana.add("Bandlavagu");
		damsInTelangana.add("Bazarthathnur");
		damsInTelangana.add("Bethampudi");
		damsInTelangana.add("Bheemanpally");
		damsInTelangana.add("Boggulavagu");
		damsInTelangana.add("Boath");
		damsInTelangana.add("Chelamelavagu");
		damsInTelangana.add("Budhpur");
		damsInTelangana.add("Choutaplly Hanuman Reddy Lift");
		damsInTelangana.add("Danpakanicheru");
		damsInTelangana.add("Devathlacheru");
		damsInTelangana.add("Dharamsagar");
		damsInTelangana.add("Fox Sagar");
		damsInTelangana.add("Dindi");
		damsInTelangana.add("Gandipally");
		damsInTelangana.add("Ghanpur Lake");
		damsInTelangana.add("Gidda Cheru");
		damsInTelangana.add("Gopaldinne");
		damsInTelangana.add("Gudipalligattu");
		damsInTelangana.add("Gujjulavagu");
		damsInTelangana.add("Gundetivagu Cheroo");
		damsInTelangana.add("Gundlavagu");
		damsInTelangana.add("Himayat Sagar");
		damsInTelangana.add("Indirammasagar");
		damsInTelangana.add("Jutpally Weir");
		damsInTelangana.add("Kaddam");
		damsInTelangana.add("Kajjerla Anicut");
		damsInTelangana.add("Kakarvani");
		damsInTelangana.add("Kandlapalle Cheruvu");
		damsInTelangana.add("Kesavari Samudram");
		damsInTelangana.add("Kaddam");
		damsInTelangana.add("Kinnerasani");
		damsInTelangana.add("Koil Sagar");
		damsInTelangana.add("Komaram Bheem");
		damsInTelangana.add("Komsettipally");
		damsInTelangana.add("Kothacheru");
		damsInTelangana.add("Kotipally Vagu");
		damsInTelangana.add("Koulasanala");
		damsInTelangana.add("Krishnasamudram");
		damsInTelangana.add("Kuppakanti");
		damsInTelangana.add("Lakhnapur");
		damsInTelangana.add("Lakhnavaram");
		damsInTelangana.add("Lankasagar");
		damsInTelangana.add("Adloor Yellareddy");
		damsInTelangana.add("Bibipet");
		damsInTelangana.add("Brahmanpally");
		damsInTelangana.add("Dharmaraopet");
		damsInTelangana.add("Garepally(V), Sultanabad(M)");
		damsInTelangana.add("Garla");
		damsInTelangana.add("Husnabad");
		damsInTelangana.add("Ibrahimpatnam");
		damsInTelangana.add("Husnabad");
		damsInTelangana.add("Indalwai(V)");
		damsInTelangana.add("Jangampally");
		damsInTelangana.add("Kachapur");
		damsInTelangana.add("Kamareddy");
		damsInTelangana.add("Kapuram(V)");
		damsInTelangana.add("Khajar(V)");
		damsInTelangana.add("Manchippa(V)");
		damsInTelangana.add("Mustabad (V)");
		damsInTelangana.add("Ped allareddy");
		damsInTelangana.add("Pulkal");
		damsInTelangana.add("Raviryal");
		damsInTelangana.add("Shameerpet");
		damsInTelangana.add("Sultanabad(V&M)");
		damsInTelangana.add("Uppalwai");
		damsInTelangana.add("Vilasagar (V)");
		damsInTelangana.add("Lower Manair");
		damsInTelangana.add("Mamdabad");
		damsInTelangana.add("Mallammacheruvu Saralnagar");
		damsInTelangana.add("Malluruvagu");
		damsInTelangana.add("Medi Cheru, Adavi Srirampur(V)");
		damsInTelangana.add("Melammacheru");
		damsInTelangana.add("Mid Manair");
		damsInTelangana.add("Modikuntavagu");
		damsInTelangana.add("Mothe Cheruvu");
		damsInTelangana.add("Mukkamamidi");
		damsInTelangana.add("Mulavagu");
		damsInTelangana.add("Munneru - New , Munnuru, Somaram");
		damsInTelangana.add("Mupparam");
		damsInTelangana.add("Musi");
		damsInTelangana.add("Nagarjuna Sagar");
		damsInTelangana.add("Nagarjunasagar Tail Pond");
		damsInTelangana.add("Nallacheru");
		damsInTelangana.add("Nallavagu");
		damsInTelangana.add("Namaz Cheru");
		damsInTelangana.add("Nandivagu");
		damsInTelangana.add("Neelwai");
		damsInTelangana.add("Bellempally");
		damsInTelangana.add("Kothur");
		damsInTelangana.add("Nizam Sagar");
		damsInTelangana.add("Ookachettivagu");
		damsInTelangana.add("Oora Cheru");
		damsInTelangana.add("Osman Sagar");
		damsInTelangana.add("Pakhal Lake");
		damsInTelangana.add("Palair");
		damsInTelangana.add("Palemvagu");
		damsInTelangana.add("Pedda Cheru");
		damsInTelangana.add("Pedda Cheru, Challasamudram");
		damsInTelangana.add("Pedda Cheru, Chintapalli");
		damsInTelangana.add("Pedda Cheru, Inapur");
		damsInTelangana.add("Pedda Cheru, Indurthy");
		
		Collection<String> damsInTripura = new ArrayList<String>();
		
		damsInTripura.add("Gumti Hydro");
		
		Collection<String> damsInUttarakhand = new ArrayList<String>();
		
		damsInUttarakhand.add("Baigul");
		damsInUttarakhand.add("Baur");
		damsInUttarakhand.add("Bhimtal");
		damsInUttarakhand.add("Dhauliganga");
		damsInUttarakhand.add("Dhora");
		damsInUttarakhand.add("Haripura");
		damsInUttarakhand.add("Jamrani");
		damsInUttarakhand.add("Ichari");
		damsInUttarakhand.add("Koteshwar");
		damsInUttarakhand.add("Lakhwar");
		damsInUttarakhand.add("Maneri");
		damsInUttarakhand.add("Nanak Sagar");
		damsInUttarakhand.add("Ramganga");
		damsInUttarakhand.add("Tehri");
		damsInUttarakhand.add("Tumaria");
	
		Collection<String> damsInUttarPradesh = new ArrayList<String>();
		
		damsInUttarPradesh.add("Afzalgarh");
		damsInUttarPradesh.add("Adwa");
		damsInUttarPradesh.add("Ahraura");
		damsInUttarPradesh.add("Arjun");
		damsInUttarPradesh.add("Aunjhar");
		damsInUttarPradesh.add("Bachara");
		damsInUttarPradesh.add("Baghel Khand");
		damsInUttarPradesh.add("Baghla");
		damsInUttarPradesh.add("Balui Bandh");
		damsInUttarPradesh.add("Balui");
		damsInUttarPradesh.add("Banjari Kalan");
		damsInUttarPradesh.add("Barwa");
		damsInUttarPradesh.add("Barwa Sagar");
		damsInUttarPradesh.add("Barwar");
		damsInUttarPradesh.add("Barwatola ");
		damsInUttarPradesh.add("Bhagwan pur");
		damsInUttarPradesh.add("Bhainsora");
		damsInUttarPradesh.add("Bhonka");
		damsInUttarPradesh.add("Chandra Prabha");
		damsInUttarPradesh.add("Chandrawal");
		damsInUttarPradesh.add("Chittaurgarh");
		damsInUttarPradesh.add("Deori");
		damsInUttarPradesh.add("Dhandhraul");
		damsInUttarPradesh.add("Dhenkwan");
		damsInUttarPradesh.add("Dongia");
		damsInUttarPradesh.add("Ganeshpur");
		damsInUttarPradesh.add("Dongri");
		damsInUttarPradesh.add("Garhwa");
		damsInUttarPradesh.add("Ghoori");
		damsInUttarPradesh.add("Ghooga");
		damsInUttarPradesh.add("Girgity");
		damsInUttarPradesh.add("Gointha");
		damsInUttarPradesh.add("Gularia");
		damsInUttarPradesh.add("Govind Sagar");
		damsInUttarPradesh.add("Gunta");
		damsInUttarPradesh.add("Hinauti");
		damsInUttarPradesh.add("Jaiwanti");
		damsInUttarPradesh.add("Jaiwanti");
		damsInUttarPradesh.add("Jamini");
		damsInUttarPradesh.add("Jirgo");
		damsInUttarPradesh.add("Jogendra");
		damsInUttarPradesh.add("Kachnoda");
		damsInUttarPradesh.add("Kabrai");
		damsInUttarPradesh.add("Kargara");
		damsInUttarPradesh.add("Keolari");
		damsInUttarPradesh.add("Khairman");
		damsInUttarPradesh.add("Khandeha ");
		damsInUttarPradesh.add("Khapatia");
		damsInUttarPradesh.add("Khirihata");
		damsInUttarPradesh.add("Kohar Gaddi");
		damsInUttarPradesh.add("Kota");
		damsInUttarPradesh.add("Kotra Khambha");
		damsInUttarPradesh.add("Kuba Khurd");
		damsInUttarPradesh.add("Lachura");
		damsInUttarPradesh.add("Lower Khajuri");
		damsInUttarPradesh.add("Majhgawan");
		damsInUttarPradesh.add("Matatila");
		damsInUttarPradesh.add("Maudaha");
		damsInUttarPradesh.add("Meja");
		damsInUttarPradesh.add("Moosakhand");
		damsInUttarPradesh.add("Muirpur");
		damsInUttarPradesh.add("Murtia");
		damsInUttarPradesh.add("Nagwa");
		damsInUttarPradesh.add("Nanauti");
		damsInUttarPradesh.add("Narson");
		damsInUttarPradesh.add("Naugarh");
		damsInUttarPradesh.add("Newari");
		damsInUttarPradesh.add("Obra");
		damsInUttarPradesh.add("Ohen");
		damsInUttarPradesh.add("Pachwara Lake");
		damsInUttarPradesh.add("Pahari");
		damsInUttarPradesh.add("Pahuj");
		damsInUttarPradesh.add("Patharai");
		damsInUttarPradesh.add("Pili");
		damsInUttarPradesh.add("Ragura");
		damsInUttarPradesh.add("Raipura");
		damsInUttarPradesh.add("Rajghat");
		damsInUttarPradesh.add("Rajkhar");
		damsInUttarPradesh.add("Rampur");
		damsInUttarPradesh.add("Rampur Kalyangarh");
		damsInUttarPradesh.add("Rampur Pindaria");
		damsInUttarPradesh.add("Rihand");
		damsInUttarPradesh.add("Rohini");
		damsInUttarPradesh.add("Saktesh Garh");
		damsInUttarPradesh.add("Sajnam");
		damsInUttarPradesh.add("Saprar");
		damsInUttarPradesh.add("Sarda Sagar");
		damsInUttarPradesh.add("Sarai Garh");
		damsInUttarPradesh.add("Shahjad");
		damsInUttarPradesh.add("Semri");
		damsInUttarPradesh.add("Siori Lake");
		damsInUttarPradesh.add("Sukhra");
		damsInUttarPradesh.add("Sirsi");
		damsInUttarPradesh.add("Suswar");
		damsInUttarPradesh.add("Upper Khajuri");
		damsInUttarPradesh.add("Urmil");
		damsInUttarPradesh.add("Vijaipur");
				
		/*System.out.println("Andra pradesh : " +damsInAndraPradesh.size());
		System.out.println("Arunchal pradesh : " +damsInArunachalPradesh.size());
		System.out.println("assam : " +damsInAssam.size());
		System.out.println("Bihar : " +damsInBihar.size());
		System.out.println("Chattisgarh : " +damsInChattisgarh.size());
		System.out.println("Goa : " +damsInGoa.size());
		System.out.println("Gujarat : " +damsInGujarat.size());
		System.out.println("Haryana : " +damsInHaryana.size());
		System.out.println("Jharkhand : " +damsInJharkhand.size());
		System.out.println("Himachal pradesh : " +damsInHimachalPradesh.size());
		System.out.println("Karnataka : " +damsInKarnataka.size());
		System.out.println("Kerala : " +damsInKerala.size());
		System.out.println("Madhya pradesh : " +damsInMadhyaPradesh.size());
		System.out.println("Maharastra : " +damsInMaharastra.size());
		System.out.println("Manipur : " +damsInManipur.size());
		System.out.println("Megalaya : " +damsInMegalay.size());
		System.out.println("Mizoram : " +damsInMizoram.size());
		System.out.println("Nagaland : " +damsInNagaland.size());
		System.out.println("odisha : " +damsInOdisha.size());
		System.out.println("Punjab : " +damsInPunjab.size());
		System.out.println("Rajastan : " +damsInRajasthan.size());
		System.out.println("Sikkim : " +damsInSikkim.size());
		System.out.println("Tamil nadu : " +damsInTamilNadu.size());
		System.out.println("Telangana : " +damsInTelangana.size());
		System.out.println("Tripura : " +damsInTripura.size());
		System.out.println("Uttarkhand : " +damsInUttarakhand.size());
		System.out.println("Uttar pradesh : " +damsInUttarPradesh.size());
		System.out.println("West Bengal : " +damsInWestBengal.size());
		*/
		
		Collection<String> totalDams = new ArrayList<String>();
		
		totalDams.addAll(damsInAndraPradesh);
		totalDams.addAll(damsInArunachalPradesh);
		totalDams.addAll(damsInAssam);
		totalDams.addAll(damsInBihar);
		totalDams.addAll(damsInChattisgarh);
		totalDams.addAll(damsInGoa);
		totalDams.addAll(damsInGujarat);
		totalDams.addAll(damsInHaryana);
		totalDams.addAll(damsInHimachalPradesh);
		totalDams.addAll(damsInJharkhand);
		totalDams.addAll(damsInKarnataka);
		totalDams.addAll(damsInKerala);
		totalDams.addAll(damsInMadhyaPradesh);
		totalDams.addAll(damsInMaharastra);
		totalDams.addAll(damsInManipur);
		totalDams.addAll(damsInMegalay);
		totalDams.addAll(damsInMizoram);
		totalDams.addAll(damsInNagaland);
		totalDams.addAll(damsInOdisha);
		totalDams.addAll(damsInPunjab);
		totalDams.addAll(damsInRajasthan);
		totalDams.addAll(damsInSikkim);
		totalDams.addAll(damsInTamilNadu);
		totalDams.addAll(damsInTelangana);
		totalDams.addAll(damsInTripura);
		totalDams.addAll(damsInUttarakhand);
		totalDams.addAll(damsInUttarPradesh);
		totalDams.addAll(damsInWestBengal);
		
		System.out.println(totalDams);
		
		Iterator<String> iterator = totalDams.iterator();
		
		while (iterator.hasNext()) {
			String string = iterator.next();
			
			if(string.startsWith("T")) {
				System.out.println("name of dams starting with T are : " +string);
			}
			
		}
		
		Iterator<String> dams = totalDams.iterator();
		
		while (dams.hasNext()) {
			String end = (String) dams.next();
			
			if (end.endsWith("ra")) {
				System.out.println("name of dams starting with T are : " +end);
			}
		}
		
		Iterator<String> characters = totalDams.iterator();
		
		while (characters.hasNext()) {
			String str = characters.next();
			
			if (str.length()>15) {
				System.out.println("dams name length is greater than 15 : " +str);
			}
		}
		
		Iterator<String> cases = totalDams.iterator();
		
		while (cases.hasNext()) {
			String string = cases.next();
			String str = string.toUpperCase();
		
			System.out.println(str);
		}
		
		Iterator<String> lower = totalDams.iterator();
		
		while (lower.hasNext()) {
			String string = lower.next();
			String str = string.toLowerCase();
			System.out.println(str);
		}
		
		Iterator<String> remove = totalDams.iterator();
			
		while (remove.hasNext()) {
			String string = remove.next();
			
			if (string.contains("p")|| string.contains("P")) {
				
				System.out.println("removing dams which has letter p : " +string);
				remove.remove();
			}
		}
		
		System.out.println(totalDams);
		
	}
	
	
	
}
